# Site settings
title: Tools for Information Literacy 
tagline: INLS161-001 (Summer II)
description: "Tools and concepts for information literacy. Includes software use and maintenance, computer applications, and networked information systems."
baseurl: ""
url: "http://inls161.johndmart.in"

name: John D. Martin III
email: john.d.martin.iii@unc.edu
twitter_username: jdmar3
github_username:  jdmar3

department: INLS
course-number: "161"
course-section: "001"
course-term: Summer II

officehours: I will be available for a half hour before and after our Lab sessions and also by appointment. 

location: 117 Manning Hall (computer lab inside the SILS library)
hours: "1100 - 1230"
days: MoTuWeThFr
dates: "22 June - 23 July 2015"
exam: 27 July 2015

acknowledgements: I would like to thank Ron Bergquist, upon whose course much of the content of this course is based, as well as all of those who have taught this course over the years since it was originated at SILS. 

credits: This page was generated by <a href="https://pages.github.com">GitHub Pages</a> using a slightly modified version of the <a href="https://github.com/jasonlong/architect-theme">Architect theme</a> by <a href="https://twitter.com/jasonlong">Jason Long</a>. <a href="https://github.com/pietromenna/jekyll-architect-theme">jekyll-architect-theme</a> is maintained by <a href="https://github.com/pietromenna">pietromenna</a>.

# Build settings
markdown: kramdown
#markdown: redcarpet
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
permalink: pretty

