# Site settings
title: Tools for Information Literacy 
subtitle: INLS161-001 (Summer II)
description: "Tools and concepts for information literacy. Includes software use and maintenance, computer applications, and networked information systems."
baseurl: ""
#baseurl: "http://ils.unc.edu/courses/2016_summerII/inls161_001"
url: "https://inls161.johndmart.in"
enforce-ssl: "inls161.johndmart.in"
#url: http://ils.unc.edu/courses/2016_summerII/inls161_001/

#name: John D. Martin III
#email: john.d.martin.iii@unc.edu
#twitter_username: jdmar3
#github_username:  jdmar3

mainicon: "/assets/img/161icon.png"

department: INLS
course-number: "161"
course-section: "001"
course-term: Summer II
course-year: "2016"
dates: 20 June 2016 - 25 July 2016
exam: 25 July 2016 (11:30-14:30)

acknowledgements: I would like to thank Ron Bergquist, upon whose course much of the content of this course is based, as well as all of those who have taught this course over the years since it was originated at SILS. 

credits: This page was generated by <a href="https://pages.github.com">GitHub Pages</a> using a slightly modified version of the <a href="https://github.com/jasonlong/architect-theme">Architect theme</a> by <a href="https://twitter.com/jasonlong">Jason Long</a>. <a href="https://github.com/pietromenna/jekyll-architect-theme">jekyll-architect-theme</a> is maintained by <a href="https://github.com/pietromenna">pietromenna</a>.

license: '<a rel="license" href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en_US"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png"></a> This work is licensed under a <a rel="license" href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en_US">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 Unported License</a>.'

# When mothballed, assignments link to assignments/a#.md 
mothballed: true    

# Build settings

future: true

#markdown: kramdown
markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data", "superscript"]

markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: pretty
timezone: America/New_York

excerpt_separator: <excerpt/>  # you can specify your own separator, of course.

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/workspace/jdmar3.github.io
