# Site settings
title: Tools for Information Literacy 
subtitle: INLS161-001 (Summer II)
description: "Tools and concepts for information literacy. Includes software use and maintenance, computer applications, and networked information systems."

## Comment this section if setting up an archive site ##################
#baseurl: ""
#url: "https://inls161.johndmart.in"
#enforce-ssl: "inls161.johndmart.in"
########################################################################

## Uncomment this section if setting up an archive site ################
url: "https://ils.unc.edu"
baseurl: "/courses/2016_summerII/inls161_001"
enforce-ssl: "ils.unc.edu"
# When mothballed assignments link to statics and there is a GH link
mothballed: true  
########################################################################

#name: John D. Martin III
#email: john.d.martin.iii@unc.edu
#twitter_username: jdmar3
#github_username:  jdmar3

mainicon: "/assets/img/161icon.png"

department: INLS
course-number: "161"
course-section: "001"
course-term: Summer II
course-year: "2016"
dates: 20 June 2016 - 25 July 2016
exam: 25 July 2016 (11:30-14:30)

acknowledgements: "I would like to thank Ron Bergquist, upon whose course much of the content of this course is based, as well as all of those who have taught this course over the years since it was originated at SILS."

license: 'All content licensed under a <a target="_blank" rel="license" href="https://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License</a>.'

license-img: '<a target="_blank" rel="license" href="https://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="CC-BY-NC-SA" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png" /></a>'

license-img-lrg: '<a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/"><img alt="CC-BY-NC-SA" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a>'

license-summary: 'You may redistribute, remix, or copy content on this site under the same license as above for non-commercial purposes provided that you provide attribution and link back to the source.'

theme-license: '<a href="https://github.com/clayh53/tufte-jekyll">Tufte-Jekyll theme</a> is &copy; <a href="http://www.clayharmon.com/">Clay Harmon</a> and distributed under the MIT license. This site theme is also distributed under the MIT license.'

credits: 'This page was generated by <a href="https://pages.github.com">GitHub Pages</a> using a heavily modified version of the <a href="https://github.com/clayh53/tufte-jekyll">Tufte-Jekyll theme</a> by <a href="http://www.clayharmon.com/">Clay Harmon</a>.'

# When mothballed, assignments link to assignments/a#.md 
mothballed: true    

# Build settings

future: true

#markdown: kramdown
markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data", "superscript"]

markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: pretty
timezone: America/New_York

excerpt_separator: <excerpt/>  # you can specify your own separator, of course.

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/workspace/jdmar3.github.io
